export const errorConstants = {
    'ALREADY_EXISTING_USER': 'ALREADY_EXISTING_USER',
    'MISSING_USER': 'MISSING_USER',
    'MISSING_USER_ID': 'MISSING_USER_ID',
    'MISSING_GENRE_ID': 'MISSING_GENRE_ID',
    'MISSING_MOVIE_ID': 'MISSING_MOVIE_ID',
    'STORING_DATA_FAILED': 'STORING_DATA_FAILED'
}